version: "3.8"

services:
  hadoop-pig:
    image: suhothayan/hadoop-spark-pig-hive:2.9.2
    container_name: sd-t3-hadoop-pig
    hostname: sd-t3-hadoop-pig
    stdin_open: true
    tty: true
    ports:
      - "50070:50070"   # HDFS UI
      - "8088:8088"     # YARN UI
      - "8080:8080"     # Spark/Hive UI
    volumes:
      # 1. Mapeamos tu carpeta de experimentos local a /data en el contenedor
      - ./experiments_results/Tarea3:/data
      
      # 2. Mapeamos tu carpeta de servicios local a /pig en el contenedor
      - ./Servicios/HadoopPig:/pig